config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :boards do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#


class Board < ApplicationRecord
    has_one_attached :eyecatch
    belongs_to :user


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :boards, dependent: :destroy

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @boards = Board.all
    end

    def show
    end

    def new
        @board = Board.new
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board),notice: '保存できたよ'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new, status: :unprocessable_entity
        end
    end


    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました', status: :see_other
    end

    private
    def board_params
        params.require(:board).permit(:title, :content, :eyecatch)
    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true ) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class:'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true ) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class:'btn-primary'

app/views/boards/index.html.haml
.container
  .tab
    All Boards
  - @boards.each do |board|
    = render 'commons/board', board: board
  = link_to new_board_path do
    .float_btn
      +Add new board

app/views/boards/new.html.haml
/= render 'form', board: @board
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true ) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class:'btn-primary'
/boardを@boardに変更

app/views/boards/show.html.haml
.board
  %h1.board_title= @board.title
  .board_detail_actions
    .dropdown
      = image_tag 'actions.png', class: 'dropbtn'
      .dropdown-content.mini
        = link_to '編集する', edit_board_path(@board)
        = link_to '削除する', board_path(@board), data: { turbo_method: :delete, turbo_confirm: '本当に削除してもよろしいですか？' }
  - if @board.eyecatch.attached?
    .board_image
      = image_tag @board.eyecatch
  .board_content
    = @board.content

app/views/commons/_board.html.haml
= link_to board_path(board) do
  .card
    - if board.eyecatch.attached?
      .board_image
        = image_tag board.eyecatch
    .card_content
      .card_title
        = board.title
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  %body
    %header.header
      .header_logos
        %p.header_pageTitle
          = link_to 'Borads', root_path
    %hr
    - if flash.present?
      .flash
        - flash.each do |key,value|
          %div{:class => key}= value
    = yield